# Generated by Django 3.2.13 on 2023-02-14 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230214_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='stars',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
